/*
  File autogenerated by gengetopt version 2.23
  generated with the following command:
  gengetopt --no-handle-error --no-version

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "generates code to load functions using the dlopen() API";

const char *gengetopt_args_info_usage = "Usage: gendlopen [OPTION]...";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                 Print help and exit",
  "  -i, --input=filename       Input file with C function prototype list; set\n                               filename as `-' to read from STDIN",
  "  -o, --output=filename      Output header file; if not specified the output\n                               will be printed to STDOUT",
  "  -s, --separate-files       Output to separate files (header, source);\n                               requires `--output'",
  "  -f, --force                Force overwriting of existing files",
  "  -t, --target=cpp           Target language (c, cpp, cpp-static)\n                               (default=`c')",
  "  -c, --custom=filename      Custom input template file",
  "  -n, --name=myclass         Macro prefix or C++ class name\n                               (default=`gendlopen')",
  "  -D, --def=option           Boolean custom definition",
  "  -l, --library=libname.ext  Default library name",
  "      --no-quote             Do not put quotes around default library name",
  "      --no-random            Disable appending random numbers to symbol names",
  "  -C, --convert              Convert our own type of macro conditionals to C\n                               style ones",
  "  -w, --win32                Use the win32 LoadLibrary() API",
  "      --win-linebreaks       Use Windows style line breaks (\\r\\n)",
  "  -k, --keep-spaces          Do not strip trailing whitespaces after removing a\n                               macro from the end of a line",
  "  -a, --atexit               Automatically call a function on normal program\n                               termination to free library handles (C only)",
    0
};

typedef enum {ARG_NO
  , ARG_STRING
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->input_given = 0 ;
  args_info->output_given = 0 ;
  args_info->separate_files_given = 0 ;
  args_info->force_given = 0 ;
  args_info->target_given = 0 ;
  args_info->custom_given = 0 ;
  args_info->name_given = 0 ;
  args_info->def_given = 0 ;
  args_info->library_given = 0 ;
  args_info->no_quote_given = 0 ;
  args_info->no_random_given = 0 ;
  args_info->convert_given = 0 ;
  args_info->win32_given = 0 ;
  args_info->win_linebreaks_given = 0 ;
  args_info->keep_spaces_given = 0 ;
  args_info->atexit_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->input_arg = NULL;
  args_info->input_orig = NULL;
  args_info->output_arg = NULL;
  args_info->output_orig = NULL;
  args_info->target_arg = NULL;
  args_info->target_orig = NULL;
  args_info->custom_arg = NULL;
  args_info->custom_orig = NULL;
  args_info->name_arg = NULL;
  args_info->name_orig = NULL;
  args_info->def_arg = NULL;
  args_info->def_orig = NULL;
  args_info->library_arg = NULL;
  args_info->library_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->input_help = gengetopt_args_info_help[1] ;
  args_info->output_help = gengetopt_args_info_help[2] ;
  args_info->separate_files_help = gengetopt_args_info_help[3] ;
  args_info->force_help = gengetopt_args_info_help[4] ;
  args_info->target_help = gengetopt_args_info_help[5] ;
  args_info->custom_help = gengetopt_args_info_help[6] ;
  args_info->name_help = gengetopt_args_info_help[7] ;
  args_info->def_help = gengetopt_args_info_help[8] ;
  args_info->def_min = 0;
  args_info->def_max = 0;
  args_info->library_help = gengetopt_args_info_help[9] ;
  args_info->no_quote_help = gengetopt_args_info_help[10] ;
  args_info->no_random_help = gengetopt_args_info_help[11] ;
  args_info->convert_help = gengetopt_args_info_help[12] ;
  args_info->win32_help = gengetopt_args_info_help[13] ;
  args_info->win_linebreaks_help = gengetopt_args_info_help[14] ;
  args_info->keep_spaces_help = gengetopt_args_info_help[15] ;
  args_info->atexit_help = gengetopt_args_info_help[16] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void)
{
	size_t len_purpose = strlen(gengetopt_args_info_purpose);
	size_t len_usage = strlen(gengetopt_args_info_usage);

	if (len_usage > 0) {
		printf("%s\n", gengetopt_args_info_usage);
	}
	if (len_purpose > 0) {
		printf("%s\n", gengetopt_args_info_purpose);
	}

	if (len_usage || len_purpose) {
		printf("\n");
	}

	if (strlen(gengetopt_args_info_description) > 0) {
		printf("%s\n\n", gengetopt_args_info_description);
	}
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}

/** @brief generic value variable */
union generic_value {
    char *string_arg;
    const char *default_string_arg;
};

/** @brief holds temporary values for multiple options */
struct generic_list
{
  union generic_value arg;
  char *orig;
  struct generic_list *next;
};

/**
 * @brief add a node at the head of the list 
 */
static void add_node(struct generic_list **list) {
  struct generic_list *new_node = (struct generic_list *) malloc (sizeof (struct generic_list));
  new_node->next = *list;
  *list = new_node;
  new_node->arg.string_arg = 0;
  new_node->orig = 0;
}


static void
free_multiple_string_field(unsigned int len, char ***arg, char ***orig)
{
  unsigned int i;
  if (*arg) {
    for (i = 0; i < len; ++i)
      {
        free_string_field(&((*arg)[i]));
        free_string_field(&((*orig)[i]));
      }
    free_string_field(&((*arg)[0])); /* free default string */

    free (*arg);
    *arg = 0;
    free (*orig);
    *orig = 0;
  }
}

static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{

  free_string_field (&(args_info->input_arg));
  free_string_field (&(args_info->input_orig));
  free_string_field (&(args_info->output_arg));
  free_string_field (&(args_info->output_orig));
  free_string_field (&(args_info->target_arg));
  free_string_field (&(args_info->target_orig));
  free_string_field (&(args_info->custom_arg));
  free_string_field (&(args_info->custom_orig));
  free_string_field (&(args_info->name_arg));
  free_string_field (&(args_info->name_orig));
  free_multiple_string_field (args_info->def_given, &(args_info->def_arg), &(args_info->def_orig));
  free_string_field (&(args_info->library_arg));
  free_string_field (&(args_info->library_orig));
  
  

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}

static void
write_multiple_into_file(FILE *outfile, int len, const char *opt, char **arg, const char *values[])
{
  int i;
  
  for (i = 0; i < len; ++i)
    write_into_file(outfile, opt, (arg ? arg[i] : 0), values);
}

int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->input_given)
    write_into_file(outfile, "input", args_info->input_orig, 0);
  if (args_info->output_given)
    write_into_file(outfile, "output", args_info->output_orig, 0);
  if (args_info->separate_files_given)
    write_into_file(outfile, "separate-files", 0, 0 );
  if (args_info->force_given)
    write_into_file(outfile, "force", 0, 0 );
  if (args_info->target_given)
    write_into_file(outfile, "target", args_info->target_orig, 0);
  if (args_info->custom_given)
    write_into_file(outfile, "custom", args_info->custom_orig, 0);
  if (args_info->name_given)
    write_into_file(outfile, "name", args_info->name_orig, 0);
  write_multiple_into_file(outfile, args_info->def_given, "def", args_info->def_orig, 0);
  if (args_info->library_given)
    write_into_file(outfile, "library", args_info->library_orig, 0);
  if (args_info->no_quote_given)
    write_into_file(outfile, "no-quote", 0, 0 );
  if (args_info->no_random_given)
    write_into_file(outfile, "no-random", 0, 0 );
  if (args_info->convert_given)
    write_into_file(outfile, "convert", 0, 0 );
  if (args_info->win32_given)
    write_into_file(outfile, "win32", 0, 0 );
  if (args_info->win_linebreaks_given)
    write_into_file(outfile, "win-linebreaks", 0, 0 );
  if (args_info->keep_spaces_given)
    write_into_file(outfile, "keep-spaces", 0, 0 );
  if (args_info->atexit_given)
    write_into_file(outfile, "atexit", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static char *
get_multiple_arg_token(const char *arg)
{
  const char *tok;
  char *ret;
  size_t len, num_of_escape, i, j;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');
  num_of_escape = 0;

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
          ++num_of_escape;
        }
      else
        break;
    }

  if (tok)
    len = (size_t)(tok - arg + 1);
  else
    len = strlen (arg) + 1;

  len -= num_of_escape;

  ret = (char *) malloc (len);

  i = 0;
  j = 0;
  while (arg[i] && (j < len-1))
    {
      if (arg[i] == '\\' && 
	  arg[ i + 1 ] && 
	  arg[ i + 1 ] == ',')
        ++i;

      ret[j++] = arg[i++];
    }

  ret[len-1] = '\0';

  return ret;
}

static const char *
get_multiple_arg_token_next(const char *arg)
{
  const char *tok;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
        }
      else
        break;
    }

  if (! tok || strlen(tok) == 1)
    return 0;

  return tok+1;
}

static int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc);

int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc)
{
  int error_occurred = 0;

  if (option_given && (min > 0 || max > 0))
    {
      if (min > 0 && max > 0)
        {
          if (min == max)
            {
              /* specific occurrences */
              if (option_given != (unsigned int) min)
                {
                  fprintf (stderr, "%s: %s option occurrences must be %d\n",
                    prog_name, option_desc, min);
                  error_occurred = 1;
                }
            }
          else if (option_given < (unsigned int) min
                || option_given > (unsigned int) max)
            {
              /* range occurrences */
              fprintf (stderr, "%s: %s option occurrences must be between %d and %d\n",
                prog_name, option_desc, min, max);
              error_occurred = 1;
            }
        }
      else if (min > 0)
        {
          /* at least check */
          if (option_given < min)
            {
              fprintf (stderr, "%s: %s option occurrences must be at least %d\n",
                prog_name, option_desc, min);
              error_occurred = 1;
            }
        }
      else if (max > 0)
        {
          /* at most check */
          if (option_given > max)
            {
              fprintf (stderr, "%s: %s option occurrences must be at most %d\n",
                prog_name, option_desc, max);
              error_occurred = 1;
            }
        }
    }
    
  return error_occurred;
}
int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (check_multiple_option_occurrences(prog_name, args_info->def_given, args_info->def_min, args_info->def_max, "'--def' ('-D')"))
     error_occurred = 1;
  
  
  /* checks for dependences among options */

  return error_occurred;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

	FIX_UNUSED(stop_char);
	
  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}

/**
 * @brief store information about a multiple option in a temporary list
 * @param list where to (temporarily) store multiple options
 */
static
int update_multiple_arg_temp(struct generic_list **list,
               unsigned int *prev_given, const char *val,
               const char *possible_values[], const char *default_value,
               cmdline_parser_arg_type arg_type,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  /* store single arguments */
  char *multi_token;
  const char *multi_next;

  if (arg_type == ARG_NO) {
    (*prev_given)++;
    return 0; /* OK */
  }

  multi_token = get_multiple_arg_token(val);
  multi_next = get_multiple_arg_token_next (val);

  while (1)
    {
      add_node (list);
      if (update_arg((void *)&((*list)->arg), &((*list)->orig), 0,
          prev_given, multi_token, possible_values, default_value, 
          arg_type, 0, 1, 1, 1, long_opt, short_opt, additional_error)) {
        if (multi_token) free(multi_token);
        return 1; /* failure */
      }

      if (multi_next)
        {
          multi_token = get_multiple_arg_token(multi_next);
          multi_next = get_multiple_arg_token_next (multi_next);
        }
      else
        break;
    }

  return 0; /* OK */
}

/**
 * @brief free the passed list (including possible string argument)
 */
static
void free_list(struct generic_list *list, short string_arg)
{
  if (list) {
    struct generic_list *tmp;
    while (list)
      {
        tmp = list;
        if (string_arg && list->arg.string_arg)
          free (list->arg.string_arg);
        if (list->orig)
          free (list->orig);
        list = list->next;
        free (tmp);
      }
  }
}

/**
 * @brief updates a multiple option starting from the passed list
 */
static
void update_multiple_arg(void *field, char ***orig_field,
               unsigned int field_given, unsigned int prev_given, union generic_value *default_value,
               cmdline_parser_arg_type arg_type,
               struct generic_list *list)
{
  int i;
  struct generic_list *tmp;

  if (prev_given && list) {
    *orig_field = (char **) realloc (*orig_field, (field_given + prev_given) * sizeof (char *));

    switch(arg_type) {
    case ARG_STRING:
      *((char ***)field) = (char **)realloc (*((char ***)field), (field_given + prev_given) * sizeof (char *)); break;
    default:
      break;
    };
    
    for (i = (prev_given - 1); i >= 0; --i)
      {
        tmp = list;
        
        switch(arg_type) {
        case ARG_STRING:
          (*((char ***)field))[i + field_given] = tmp->arg.string_arg; break;
        default:
          break;
        }        
        (*orig_field) [i + field_given] = list->orig;
        list = list->next;
        free (tmp);
      }
  } else { /* set the default value */
    if (default_value && ! field_given) {
      switch(arg_type) {
      case ARG_STRING:
        if (! *((char ***)field)) {
          *((char ***)field) = (char **)malloc (sizeof (char *));
          (*((char ***)field))[0] = gengetopt_strdup(default_value->string_arg);
        }
        break;
      default: break;
      }
      if (!(*orig_field)) {
        *orig_field = (char **) malloc (sizeof (char *));
        (*orig_field)[0] = 0;
      }
    }
  }
}

int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  struct generic_list * def_list = NULL;
  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  /* TODO: Why is this here? It is not used anywhere. */
  override = params->override;
  FIX_UNUSED(override);

  initialize = params->initialize;
  check_required = params->check_required;

  /* TODO: Why is this here? It is not used anywhere. */
  check_ambiguity = params->check_ambiguity;
  FIX_UNUSED(check_ambiguity);

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "input",	1, NULL, 'i' },
        { "output",	1, NULL, 'o' },
        { "separate-files",	0, NULL, 's' },
        { "force",	0, NULL, 'f' },
        { "target",	1, NULL, 't' },
        { "custom",	1, NULL, 'c' },
        { "name",	1, NULL, 'n' },
        { "def",	1, NULL, 'D' },
        { "library",	1, NULL, 'l' },
        { "no-quote",	0, NULL, 0 },
        { "no-random",	0, NULL, 0 },
        { "convert",	0, NULL, 'C' },
        { "win32",	0, NULL, 'w' },
        { "win-linebreaks",	0, NULL, 0 },
        { "keep-spaces",	0, NULL, 'k' },
        { "atexit",	0, NULL, 'a' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hi:o:sft:c:n:D:l:Cwka", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'i':	/* Input file with C function prototype list; set filename as `-' to read from STDIN.  */
        
        
          if (update_arg( (void *)&(args_info->input_arg), 
               &(args_info->input_orig), &(args_info->input_given),
              &(local_args_info.input_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "input", 'i',
              additional_error))
            goto failure;
        
          break;
        case 'o':	/* Output header file; if not specified the output will be printed to STDOUT.  */
        
        
          if (update_arg( (void *)&(args_info->output_arg), 
               &(args_info->output_orig), &(args_info->output_given),
              &(local_args_info.output_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "output", 'o',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* Output to separate files (header, source); requires `--output'.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->separate_files_given),
              &(local_args_info.separate_files_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "separate-files", 's',
              additional_error))
            goto failure;
        
          break;
        case 'f':	/* Force overwriting of existing files.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->force_given),
              &(local_args_info.force_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "force", 'f',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* Target language (c, cpp, cpp-static)  (default=`c').  */
        
        
          if (update_arg( (void *)&(args_info->target_arg), 
               &(args_info->target_orig), &(args_info->target_given),
              &(local_args_info.target_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "target", 't',
              additional_error))
            goto failure;
        
          break;
        case 'c':	/* Custom input template file.  */
        
        
          if (update_arg( (void *)&(args_info->custom_arg), 
               &(args_info->custom_orig), &(args_info->custom_given),
              &(local_args_info.custom_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "custom", 'c',
              additional_error))
            goto failure;
        
          break;
        case 'n':	/* Macro prefix or C++ class name  (default=`gendlopen').  */
        
        
          if (update_arg( (void *)&(args_info->name_arg), 
               &(args_info->name_orig), &(args_info->name_given),
              &(local_args_info.name_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "name", 'n',
              additional_error))
            goto failure;
        
          break;
        case 'D':	/* Boolean custom definition.  */
        
          if (update_multiple_arg_temp(&def_list, 
              &(local_args_info.def_given), optarg, 0, 0, ARG_STRING,
              "def", 'D',
              additional_error))
            goto failure;
        
          break;
        case 'l':	/* Default library name.  */
        
        
          if (update_arg( (void *)&(args_info->library_arg), 
               &(args_info->library_orig), &(args_info->library_given),
              &(local_args_info.library_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "library", 'l',
              additional_error))
            goto failure;
        
          break;
        case 'C':	/* Convert our own type of macro conditionals to C style ones.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->convert_given),
              &(local_args_info.convert_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "convert", 'C',
              additional_error))
            goto failure;
        
          break;
        case 'w':	/* Use the win32 LoadLibrary() API.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->win32_given),
              &(local_args_info.win32_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "win32", 'w',
              additional_error))
            goto failure;
        
          break;
        case 'k':	/* Do not strip trailing whitespaces after removing a macro from the end of a line.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->keep_spaces_given),
              &(local_args_info.keep_spaces_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "keep-spaces", 'k',
              additional_error))
            goto failure;
        
          break;
        case 'a':	/* Automatically call a function on normal program termination to free library handles (C only).  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->atexit_given),
              &(local_args_info.atexit_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "atexit", 'a',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* Do not put quotes around default library name.  */
          if (strcmp (long_options[option_index].name, "no-quote") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->no_quote_given),
                &(local_args_info.no_quote_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "no-quote", '-',
                additional_error))
              goto failure;
          
          }
          /* Disable appending random numbers to symbol names.  */
          else if (strcmp (long_options[option_index].name, "no-random") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->no_random_given),
                &(local_args_info.no_random_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "no-random", '-',
                additional_error))
              goto failure;
          
          }
          /* Use Windows style line breaks (\\r\\n).  */
          else if (strcmp (long_options[option_index].name, "win-linebreaks") == 0)
          {
          
          
            if (update_arg( 0 , 
                 0 , &(args_info->win_linebreaks_given),
                &(local_args_info.win_linebreaks_given), optarg, 0, 0, ARG_NO,
                check_ambiguity, override, 0, 0,
                "win-linebreaks", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */


  update_multiple_arg((void *)&(args_info->def_arg),
    &(args_info->def_orig), args_info->def_given,
    local_args_info.def_given, 0,
    ARG_STRING, def_list);

  args_info->def_given += local_args_info.def_given;
  local_args_info.def_given = 0;
  
  if (check_required)
    {
      error_occurred += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  return 0;

failure:
  free_list (def_list, 1 );
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
/* vim: set ft=c noet ts=8 sts=8 sw=8 tw=80 nojs spell : */
