/** @file cmdline.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.23
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "gendlopen"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "gendlopen"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION ""
#endif

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  char * input_arg;	/**< @brief Input file with C function prototype list; set filename as `-' to read from STDIN.  */
  char * input_orig;	/**< @brief Input file with C function prototype list; set filename as `-' to read from STDIN original value given at command line.  */
  const char *input_help; /**< @brief Input file with C function prototype list; set filename as `-' to read from STDIN help description.  */
  char * output_arg;	/**< @brief Output header file; if not specified the output will be printed to STDOUT.  */
  char * output_orig;	/**< @brief Output header file; if not specified the output will be printed to STDOUT original value given at command line.  */
  const char *output_help; /**< @brief Output header file; if not specified the output will be printed to STDOUT help description.  */
  const char *separate_files_help; /**< @brief Output to separate files (header, source); requires `--output' help description.  */
  const char *force_help; /**< @brief Force overwriting of existing files help description.  */
  char * target_arg;	/**< @brief Target language (c, cpp, cpp-static)  (default=`c').  */
  char * target_orig;	/**< @brief Target language (c, cpp, cpp-static)  (default=`c') original value given at command line.  */
  const char *target_help; /**< @brief Target language (c, cpp, cpp-static)  (default=`c') help description.  */
  char * custom_arg;	/**< @brief Custom input template file.  */
  char * custom_orig;	/**< @brief Custom input template file original value given at command line.  */
  const char *custom_help; /**< @brief Custom input template file help description.  */
  char * name_arg;	/**< @brief Macro prefix or C++ class name  (default=`gendlopen').  */
  char * name_orig;	/**< @brief Macro prefix or C++ class name  (default=`gendlopen') original value given at command line.  */
  const char *name_help; /**< @brief Macro prefix or C++ class name  (default=`gendlopen') help description.  */
  char ** def_arg;	/**< @brief Boolean custom definition.  */
  char ** def_orig;	/**< @brief Boolean custom definition original value given at command line.  */
  unsigned int def_min; /**< @brief Boolean custom definition's minimum occurreces */
  unsigned int def_max; /**< @brief Boolean custom definition's maximum occurreces */
  const char *def_help; /**< @brief Boolean custom definition help description.  */
  char * library_arg;	/**< @brief Default library name.  */
  char * library_orig;	/**< @brief Default library name original value given at command line.  */
  const char *library_help; /**< @brief Default library name help description.  */
  const char *no_quote_help; /**< @brief Do not put quotes around default library name help description.  */
  const char *no_random_help; /**< @brief Disable appending random numbers to symbol names help description.  */
  const char *convert_help; /**< @brief Convert our own type of macro conditionals to C style ones help description.  */
  const char *win32_help; /**< @brief Use the win32 LoadLibrary() API help description.  */
  const char *win_linebreaks_help; /**< @brief Use Windows style line breaks (\\r\\n) help description.  */
  const char *keep_spaces_help; /**< @brief Do not strip trailing whitespaces after removing a macro from the end of a line help description.  */
  const char *atexit_help; /**< @brief Automatically call a function on normal program termination to free library handles (C only) help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int input_given ;	/**< @brief Whether input was given.  */
  unsigned int output_given ;	/**< @brief Whether output was given.  */
  unsigned int separate_files_given ;	/**< @brief Whether separate-files was given.  */
  unsigned int force_given ;	/**< @brief Whether force was given.  */
  unsigned int target_given ;	/**< @brief Whether target was given.  */
  unsigned int custom_given ;	/**< @brief Whether custom was given.  */
  unsigned int name_given ;	/**< @brief Whether name was given.  */
  unsigned int def_given ;	/**< @brief Whether def was given.  */
  unsigned int library_given ;	/**< @brief Whether library was given.  */
  unsigned int no_quote_given ;	/**< @brief Whether no-quote was given.  */
  unsigned int no_random_given ;	/**< @brief Whether no-random was given.  */
  unsigned int convert_given ;	/**< @brief Whether convert was given.  */
  unsigned int win32_given ;	/**< @brief Whether win32 was given.  */
  unsigned int win_linebreaks_given ;	/**< @brief Whether win-linebreaks was given.  */
  unsigned int keep_spaces_given ;	/**< @brief Whether keep-spaces was given.  */
  unsigned int atexit_given ;	/**< @brief Whether atexit was given.  */

} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief the description string of the program */
extern const char *gengetopt_args_info_description;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
