/* X macros */
TEMPLATE(license.h,         license)
TEMPLATE(filename_macros.h, filename_macros)
TEMPLATE(common.h,          common_header)
TEMPLATE(common.c,          common_body)
TEMPLATE(c.h,               c_header)
TEMPLATE(c.c,               c_body)
TEMPLATE(cxx.hpp,           cxx_header)
TEMPLATE(cxx.cpp,           cxx_body)
TEMPLATE(minimal.h,         min_c_header)
TEMPLATE(minimal_cxxeh.hpp, min_cxx_header)
TEMPLATE(plugin.h,          plugin_header)
TEMPLATE(plugin.c,          plugin_body)
