#!/bin/bash

flags="""

RTLD_LAZY
RTLD_NOW
RTLD_GLOBAL
RTLD_LOCAL
RTLD_NODELETE
RTLD_NOLOAD
RTLD_DEEPBIND

DONT_RESOLVE_DLL_REFERENCES
LOAD_IGNORE_CODE_AUTHZ_LEVEL
LOAD_LIBRARY_AS_DATAFILE
LOAD_LIBRARY_AS_DATAFILE_EXCLUSIVE
LOAD_LIBRARY_AS_IMAGE_RESOURCE
LOAD_LIBRARY_SEARCH_APPLICATION_DIR
LOAD_LIBRARY_SEARCH_DEFAULT_DIRS
LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR
LOAD_LIBRARY_SEARCH_SYSTEM32
LOAD_LIBRARY_SEARCH_USER_DIRS
LOAD_WITH_ALTERED_SEARCH_PATH
LOAD_LIBRARY_REQUIRE_SIGNED_TARGET
LOAD_LIBRARY_SAFE_CURRENT_DIRS

"""

for flag in $flags ; do
    echo "#ifndef $flag"
    echo "#define $flag 0"
    echo "#endif"
done
