name: meson build and test
on: [check_run, push, pull_request, workflow_dispatch]
jobs:
  meson-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:     
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install meson ninja
      - name: Meson configure
        run: meson setup build -Denable_tests=true -Denable_examples=true -Denable_utf8=true
      - name: Meson compile
        run: meson compile -C build -v
      - name: Run tests
        run: meson test -C build
